name: "Convert todo to issue"
on: ["push"]
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@master"
      - name: "Convert todo to GitHub Issue"
        uses: "alstr/todo-to-issue-action@v4.6"
        id: "todo"